export interface Country {
  label: string;
  value: string;
  dialCode: string; // Thêm dialCode cho thông tin số vùng
}
export interface CountryPickerProps {
  onValueChange: (value: string, dialCode: string) => void;
}
export const Datacountries: Country[] = [
  {label: 'United States', value: 'usa', dialCode: '+1'},
  {label: 'Canada', value: 'canada', dialCode: '+1'},
  {label: 'United Kingdom', value: 'uk', dialCode: '+44'},
  {label: 'Australia', value: 'au', dialCode: '+61'},
  {label: 'India', value: 'in', dialCode: '+91'},
  {label: 'China', value: 'cn', dialCode: '+86'},
  {label: 'Germany', value: 'de', dialCode: '+49'},
  {label: 'France', value: 'fr', dialCode: '+33'},
  {label: 'Brazil', value: 'br', dialCode: '+55'},
  {label: 'Russia', value: 'ru', dialCode: '+7'},
  {label: 'Japan', value: 'jp', dialCode: '+81'},
  {label: 'South Korea', value: 'kr', dialCode: '+82'},
  {label: 'Mexico', value: 'mx', dialCode: '+52'},
  {label: 'Italy', value: 'it', dialCode: '+39'},
  {label: 'Spain', value: 'es', dialCode: '+34'},
  {label: 'Netherlands', value: 'nl', dialCode: '+31'},
  {label: 'Switzerland', value: 'ch', dialCode: '+41'},
  {label: 'Sweden', value: 'se', dialCode: '+46'},
  {label: 'Norway', value: 'no', dialCode: '+47'},
  {label: 'Denmark', value: 'dk', dialCode: '+45'},
  {label: 'Finland', value: 'fi', dialCode: '+358'},
  {label: 'Poland', value: 'pl', dialCode: '+48'},
  {label: 'Greece', value: 'gr', dialCode: '+30'},
  {label: 'Turkey', value: 'tr', dialCode: '+90'},
  {label: 'South Africa', value: 'za', dialCode: '+27'},
  {label: 'Egypt', value: 'eg', dialCode: '+20'},
  {label: 'Nigeria', value: 'ng', dialCode: '+234'},
  {label: 'Kenya', value: 'ke', dialCode: '+254'},
  {label: 'Saudi Arabia', value: 'sa', dialCode: '+966'},
  {label: 'United Arab Emirates', value: 'ae', dialCode: '+971'},
  {label: 'Singapore', value: 'sg', dialCode: '+65'},
  {label: 'Argentina', value: 'ar', dialCode: '+54'},
  {label: 'Austria', value: 'at', dialCode: '+43'},
  {label: 'Belgium', value: 'be', dialCode: '+32'},
  {label: 'Chile', value: 'cl', dialCode: '+56'},
  {label: 'Colombia', value: 'co', dialCode: '+57'},
  {label: 'Czech Republic', value: 'cz', dialCode: '+420'},
  {label: 'Indonesia', value: 'id', dialCode: '+62'},
  {label: 'Ireland', value: 'ie', dialCode: '+353'},
  {label: 'Israel', value: 'il', dialCode: '+972'},
  {label: 'Malaysia', value: 'my', dialCode: '+60'},
  {label: 'New Zealand', value: 'nz', dialCode: '+64'},
  {label: 'Philippines', value: 'ph', dialCode: '+63'},
  {label: 'Portugal', value: 'pt', dialCode: '+351'},
  {label: 'Romania', value: 'ro', dialCode: '+40'},
  {label: 'Thailand', value: 'th', dialCode: '+66'},
  {label: 'Vietnam', value: 'vn', dialCode: '+84'},
  {label: 'Algeria', value: 'dz', dialCode: '+213'},
  {label: 'Bahrain', value: 'bh', dialCode: '+973'},
  {label: 'Bangladesh', value: 'bd', dialCode: '+880'},
  {label: 'Bulgaria', value: 'bg', dialCode: '+359'},
  {label: 'Croatia', value: 'hr', dialCode: '+385'},
  {label: 'Cyprus', value: 'cy', dialCode: '+357'},
  {label: 'Estonia', value: 'ee', dialCode: '+372'},
  {label: 'Ghana', value: 'gh', dialCode: '+233'},
  {label: 'Hong Kong', value: 'hk', dialCode: '+852'},
  {label: 'Hungary', value: 'hu', dialCode: '+36'},
  {label: 'Iceland', value: 'is', dialCode: '+354'},
  {label: 'Jordan', value: 'jo', dialCode: '+962'},
  {label: 'Kuwait', value: 'kw', dialCode: '+965'},
  {label: 'Latvia', value: 'lv', dialCode: '+371'},
  {label: 'Lebanon', value: 'lb', dialCode: '+961'},
  {label: 'Lithuania', value: 'lt', dialCode: '+370'},
  {label: 'Luxembourg', value: 'lu', dialCode: '+352'},
  {label: 'Malta', value: 'mt', dialCode: '+356'},
  {label: 'Morocco', value: 'ma', dialCode: '+212'},
  {label: 'Nepal', value: 'np', dialCode: '+977'},
  {label: 'Oman', value: 'om', dialCode: '+968'},
  {label: 'Pakistan', value: 'pk', dialCode: '+92'},
  {label: 'Peru', value: 'pe', dialCode: '+51'},
  {label: 'Qatar', value: 'qa', dialCode: '+974'},
  {label: 'Serbia', value: 'rs', dialCode: '+381'},
  {label: 'Slovakia', value: 'sk', dialCode: '+421'},
  {label: 'Slovenia', value: 'si', dialCode: '+386'},
  {label: 'Sri Lanka', value: 'lk', dialCode: '+94'},
  {label: 'Taiwan', value: 'tw', dialCode: '+886'},
  {label: 'Tunisia', value: 'tn', dialCode: '+216'},
  {label: 'Ukraine', value: 'ua', dialCode: '+380'},
  {label: 'Uruguay', value: 'uy', dialCode: '+598'},
  {label: 'Venezuela', value: 've', dialCode: '+58'},
  {label: 'Yemen', value: 'ye', dialCode: '+967'},
  {label: 'Zimbabwe', value: 'zw', dialCode: '+263'},
];
