// export {default as AuthForm} from './AuthForm';
export {default as Headers} from './Headers';
export {default as Onbroad} from './Onbroad';
export {default as AuthHeader} from './AuthHeader';
export {default as InputCustom} from './InputCustom';
export {default as SmallButton} from './SmallButton';
export {default as BigButton} from './BigButton';
export {default as Search_C} from './Search';
export {default as Switch_c} from './Switch';
export {default as TabViewitem} from './TabViewItem';
export {default as Toggleable} from './Toggleable';
