export enum routes {
  //auth
  ONBOARD = 'ONBOARD',
  SIGN_IN = 'SIGN_IN',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  LOBBY = 'LOBBY',
  UPDATE_PROFILE = 'UPDATE_PROFILE',

  BOTTOM_TAB = 'BOTTOM_TAB',

  // Chat
  CHAT = 'CHAT',
  DETAIL_CHAT = 'DETAIL_CHAT',

  // Assistant
  ASSISTANT = 'ASSISTANT',

  // History
  HISTORY = 'HISTORY',
  SEARCH_HISTORY = 'SEARCH_HISTORY',
  DETAIL_HISTORY = 'DETAIL_HISTORY',
  // Account
  ACCOUNT = 'ACCOUNT',
  PERSONAL_INFO = 'PERSONAL_INFO',
  SECURITY = 'SECURITY',
  LANGUAGE = 'LANGUAGE',
  HELP_CENTER = 'HELP_CENTER',


}
