export {default as LogoIcon} from './components/Logo';
export {default as LogoIcon_outline} from './components/Logo_outline';
export {default as DefaultAvatar} from './components/Default_avatar';
export {default as LobbyImage} from './components/LobbyImage';
export {default as Button_Send} from './components/BtnSend';
export {default as Calender_icon} from './components/Calender';
export {default as GoogleIcon} from './components/GoogleIcon';
export {default as AppleIcon} from './components/AppleIcon';
export {default as FacebookIcon} from './components/FacebookIcon';
export {default as ModalSucces} from './components/ModalSucces';
export const SvgImages = {};
